[workspace]
resolver = "3"
members = [
    "crates/arachne-domain",
    "crates/arachne-cqrs",
    "crates/arachne-net",
    "crates/arachne-parse",
    "crates/arachne-export",
    "crates/arachne",
]

[workspace.package]
edition = "2024"
license = "Apache-2.0"
publish = false

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
